[WIP] Fix logging
BlazingDB/blazingsql pull request #1038
Opened 2020-09-24 09:07 UTC by rommelDB

2020-09-25 16:26 UTC, romeluko commented
rerun tests

2020-09-25 16:27 UTC, rommelDB commented
rerun tests

2020-09-25 19:30 UTC, williamBlazing requested changes
Needs some work and also missing what we do for `_optimize_skip_data_getSlices`

2020-09-28 18:34 UTC, rommelDB commented on pyblazing/pyblazing/apiv2/context.py
> +        self.local_files = False
It makes sense. Moved to BlazingTable. Thanks.

2020-09-28 19:17 UTC, rommelDB commented on pyblazing/pyblazing/apiv2/context.py
> +        self.mapping_files = {}
Moved to BlazingTable. Thanks.

2020-09-30 16:14 UTC, merged