[WIP] MergeAggr when single node has multiple batches
BlazingDB/blazingsql pull request #1164
Opened 2020-11-17 16:53 UTC by Christian8491

This PR closes #1160

2020-11-17 17:40 UTC, Christian8491 commented
rerun tests

2020-11-17 18:56 UTC, williamBlazing requested changes

2020-11-17 18:56 UTC, williamBlazing commented on engine/src/execution_graph/logic_controllers/BatchAggregationProcessing.h
> +                if( (context->getTotalNodes() == 1) ||  (context->isMasterNode(ral::communication::CommunicationData::getInstance().getSelfNode()))  ) {
This looks like a band-aid. We need to instead figure out why if there is only one node, its not automatically the MasterNode

2020-11-17 22:05 UTC, Christian8491 commented
rerun tests

2020-11-18 15:26 UTC, ajschmidt8 commented
rerun tests

2020-11-18 20:51 UTC, Christian8491 commented
rerun tests

2020-11-18 21:51 UTC, ajschmidt8 commented
@Christian8491, Ops guy here. I reran these tests one more time. Please make sure your PR includes the changes from #1168 to prevent SSL errors.

2020-11-19 00:23 UTC, ajschmidt8 commented
rerun tests

2020-11-19 14:06 UTC, merged