[WIP] Initial support for Windows Function
BlazingDB/blazingsql pull request #1284
Opened 2021-01-15 16:10 UTC by Christian8491

The `first` target of this PR is support  in single node a basic window function which contains ONLY one `PARTITION BY` clause without `ORDER BY` clause (should be relatively easy to add it) inside the `OVER` statement.  The queries that should be supported are like this:

`"select min(n_nationkey) over ( partition by n_regionkey ) min_keys, n_nationkey, n_name, n_regionkey from nation"`

NOTE: The Window Funcion aggregations for now are those that `cudf` supports
https://github.com/rapidsai/cudf/blob/branch-0.18/cpp/include/cudf/aggregation.hpp#L57

2021-01-15 16:11 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2021-01-27 20:35 UTC, williamBlazing commented
To limit the scope and be able to get to a point where we can merge this in we still need to following:

- Add engine side validation to make sure that all the window functions run over partitions
- Add engine side validation to make sure the aggregation functions are supported. Right now we dont support lead, lag, first_value, last_value, RANK and DENSE_RANK. What others?
-  File cudf feature request issues for first_value, last_value, dense_rank. THere is already an issue for RANK, but we should add a comment there mentioning that we want it too.
- Add e2e tests where we are setting a frame with rows (i.e. ROWS BETWEEN 4 PRECEDING AND 3 FOLLOWING....)
- Add support for multiple window functions.
    - Here we will want to see if any of the OVER clauses are the same. If they are the same, we dont want to perform the global sort and all that. Otherwise we will have to have multiple global sorts

2021-01-28 23:53 UTC, williamBlazing requested changes

2021-01-28 23:53 UTC, williamBlazing commented on engine/src/execution_graph/logic_controllers/BatchWindowFunctionProcessing.cpp
> +    table_to_rolling.push_back(input_cudf_view.column(this->column_indices_partitioned[0]));
What happens if the window is partitioned by more than one column? I think here you are only considering when a window is only partitioned by one column. 
Also, this makes me realize we need e2e tests that partition by more than one column, do order by by more than one column and both.
Also please add e2e tests where there is a regular order by outside the window, to make sure that calcite and our own query parsing code does not get confused by more than one order by in the query

2021-01-29 23:43 UTC, merged