[WIP] Add queries logger to Physical plan
BlazingDB/blazingsql pull request #1311
Opened 2021-02-03 21:03 UTC by diegodfrf

Fixes #1306

2021-02-03 21:03 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2021-02-03 21:54 UTC, williamBlazing requested changes

2021-02-03 21:54 UTC, williamBlazing commented on engine/src/CalciteInterpreter.cpp
> +            queriesLogger->info("{query_id}|{step}|{substep}|{info}|||||",
The format of the queriesLogger is a little different. Its something like this:

        logger->info("{ral_id}|{query_id}|{start_time}|{plan}|{sql}",
                                        "ral_id"_a=queryContext.getNodeIndex(communicationData.getSelfNode()),
                                        "query_id"_a=queryContext.getContextToken(),
                                        "start_time"_a=eventTimer.start_time(),
                                        "plan"_a=query,
                                        "sql"_a=tree->to_string());

2021-02-03 22:24 UTC, diegodfrf commented
rerun tests

2021-02-04 15:41 UTC, williamBlazing commented
rerun-tests

2021-02-09 02:23 UTC, merged