[WIP] Window Function support for LEAD and LAG statements
BlazingDB/blazingsql pull request #1338
Opened 2021-02-18 01:20 UTC by Christian8491

* This PR removes (momentarily) the `ProjectToWindowRule` in order to get constant values correctly from queries which contains CONSTANT values (as LEAD and LAG).
* Updates the parsing at engine level to support successfully Window Functions.
* Add tests for Window Functions which contains LEAD and LAG statement.

2021-02-18 01:20 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2021-02-20 01:08 UTC, Christian8491 commented
rerun tests

2021-02-20 03:13 UTC, Christian8491 commented
rerun tests

2021-02-23 15:25 UTC, williamBlazing requested changes
Please create some unit tests for the new complex string parsing we are doing for window functions

2021-02-23 15:25 UTC, williamBlazing commented on tests/BlazingSQLTest/EndToEndTests/windowFunctionTest.py
> +
Add two more tests:
one where you have some column transformation BEFORE you have window functions and other transformation after the window functions
another one where you have some column transformation in between two window functions that have the same window frame.

2021-02-24 22:06 UTC, williamBlazing requested changes

2021-02-24 22:06 UTC, williamBlazing commented on tests/BlazingSQLTest/EndToEndTests/windowFunctionTest.py
> +                            select max(o_totalprice) over
Also add another test that does something like this:

```
                          select  o_orderkey + o_orderpriority,
                           max(o_totalprice) over
                                (
                                    partition by o_orderpriority
                                    order by o_totalprice, o_custkey
                                ) o_max_prices,
                               o_custkey + o_totalprice, 
                                min(o_totalprice) over
                                (
                                    partition by o_orderpriority
                                    order by o_totalprice, o_custkey
                                ) o_min_prices,
                                o_custkey - o_totalprice + 5
                             
                            from orders
```

2021-02-26 13:13 UTC, Christian8491 commented
rerun tests

2021-02-26 18:45 UTC, Christian8491 commented
rerun tests

2021-02-26 20:24 UTC, merged