[WIP] Freezing code flow for orc metadata
BlazingDB/blazingsql pull request #1347
Opened 2021-02-22 19:04 UTC by Christian8491

2021-02-22 19:05 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2021-02-23 01:20 UTC, williamBlazing requested changes

2021-02-23 01:20 UTC, williamBlazing commented on pyblazing/pyblazing/apiv2/context.py
> +            if (parsedSchema["file_type"] == DataType.PARQUET) or (
The `get_metadata` parameter should apply to both parquet and orc. So it should be more like this:
```
if (get_metadata and (parsedSchema["file_type"] == DataType.PARQUET or parsedSchema["file_type"] == DataType.ORC)):
```

2021-02-23 01:25 UTC, williamBlazing commented
also please add that new parameter to the comments in the beginning of `def create_table`

2021-02-23 14:15 UTC, merged