[WIP] Fix/calcite select all columns
BlazingDB/blazingsql pull request #1379
Opened 2021-03-05 18:32 UTC by Christian8491

This PR closes #1378

2021-03-05 18:32 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2021-03-09 02:50 UTC, williamBlazing requested changes

2021-03-09 02:50 UTC, williamBlazing commented on engine/src/execution_graph/logic_controllers/BatchProcessing.cpp
> +    std::vector<std::string> data_names = cache_data->names();
You need to null check cache_data first

2021-03-09 02:50 UTC, williamBlazing commented on engine/src/execution_graph/logic_controllers/BatchProcessing.cpp
> +    std::vector<std::string> data_names = cache_data->names();
also rename `data_names` to `column_names`

2021-03-09 02:50 UTC, williamBlazing commented on engine/src/execution_graph/logic_controllers/BatchProcessing.cpp
> +    std::vector<std::string> data_names = cache_data->names();
hmmm, the more i think about it, it should never be null. But to be safe, add something like `RAL_EXPECTS(cache_data != nullptr, "ERROR: Projection::run() first input CacheData was nullptr")`

2021-03-09 02:50 UTC, williamBlazing commented on engine/src/execution_graph/logic_controllers/BatchProcessing.cpp
> +    bool by_passing_project, by_passing_project_with_aliases;
bypass or bypassing is one word, not two words. So these variables should be bypassing_project, bypassing_project_with_aliases

2021-03-09 02:50 UTC, williamBlazing commented on engine/src/execution_graph/logic_controllers/BatchProcessing.cpp
> +    bool by_passing_project, by_passing_project_with_aliases;
byPassingProject should be bypassingProject

2021-03-09 15:30 UTC, merged