[WIP] Feature/unsigned types
BlazingDB/blazingsql pull request #1464
Opened 2021-04-12 17:54 UTC by Christian8491

This PR closes #1451

2021-04-12 17:54 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2021-04-14 00:11 UTC, felipeblazing requested changes

2021-04-14 00:11 UTC, felipeblazing commented on engine/src/CalciteExpressionParsing.cpp
> +		static_cast<ScalarType *>(ret.get())->set_value(static_cast<T>(LLONG_MAX));
im not sure this is the right max value here

2021-04-21 23:42 UTC, felipeblazing requested changes
can you add a few tests like select int + unsigned int and select unsigned int + unsigned int

2021-04-22 14:14 UTC, Christian8491 commented
rerun tests

2021-04-22 16:27 UTC, Christian8491 commented
rerun tests

2021-04-26 14:39 UTC, merged