[WIP] Fix Decimal/Fixed Point issue
BlazingDB/blazingsql pull request #1550
Opened 2021-05-20 19:00 UTC by Christian8491

This PR closes #1493

Notes:
* This PR does not implement support for Decimal/Fixed Point, so it's not expected you can do sql operations for this type of data.
* This PR specifically solves the issue reported.

2021-05-20 19:00 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2021-05-20 21:54 UTC, Christian8491 commented
rerun tests

2021-05-21 00:03 UTC, Christian8491 commented
rerun tests

2021-05-21 20:16 UTC, williamBlazing requested changes
Can you describe with this PR what is the behavior the engine will have when someone tries to create and/or query a table that has DECIMAL?
If the table is a cudf or parquet or orc, etc?

2021-05-21 20:24 UTC, Christian8491 commented on algebra/blazingdb-calcite-core/src/main/java/com/blazingdb/calcite/catalog/domain/CatalogColumnDataType.java
> +	DECIMAL64(26, "DECIMAL64"), ///< Fixed-point type with int64_t
I suppose new `dtypes` were added in the `cudf` side, from the time this was implemented. I can update all of them here.

2021-05-24 20:16 UTC, Christian8491 commented
rerun tests

2021-05-25 00:56 UTC, merged